
management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - health
          - logfile
          - hystrix.stream


spring:

  application:
    name: 'BrokerageApplication'
  jpa:
    show-sql: true
  data:
    rest:
      basePath: /datarest
server:
  port: 8080
logging:
  file: app.log

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000



