
management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - health
          - logfile
          - hystrix.stream


spring:

  application:
    name: 'BrokerageApplication'

  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none



  data:
    rest:
      basePath: /datarest
  h2:
    console:
       enabled:  true

  datasource:
    initialization-mode: always
    data: classpath:import.sql

server:
  port: 8080
logging:
  file: app.log

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000



